name: "Java CI"

on: ["pull_request", "push"]

jobs:
  preserve:
    runs-on: "ubuntu-latest"
    steps:
      - name: Cancel Previous Workflow Runs
        uses: n1hility/cancel-previous-runs@v2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  # build:
